# Generated by Django 4.2.5 on 2023-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
