# Generated by Django 4.2.5 on 2023-09-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Xen', '0002_alter_variants_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='product_variant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Xen.variants'),
        ),
    ]
