# Generated by Django 4.2.5 on 2023-09-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Xen', '0003_alter_productvariants_product_variant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariants',
            old_name='product_variant_name',
            new_name='variant',
        ),
    ]
