# Generated by Django 4.2.5 on 2023-09-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xen', '0004_rename_product_variant_name_productvariants_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
