# Generated by Django 4.2.5 on 2023-09-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xen', '0005_product_gimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gimage',
        ),
        migrations.AddField(
            model_name='category',
            name='gimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
