# Generated by Django 4.2.5 on 2023-09-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Xen', '0006_remove_product_gimage_category_gimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
