# Generated by Django 4.2.5 on 2023-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xen', '0009_remove_review_review_id_review_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.JSONField(default=list)),
                ('bot_response', models.JSONField(default=list)),
            ],
        ),
    ]
